# Generated by Django 3.2.7 on 2021-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramenya',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='punctuation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]),
        ),
    ]
