# Generated by Django 3.2.7 on 2021-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0002_auto_20210912_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ramenscore',
            options={'ordering': ['-total_votes']},
        ),
        migrations.RemoveField(
            model_name='ramenscore',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='punctuation',
        ),
        migrations.AddField(
            model_name='ramenscore',
            name='total_votes',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
